// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wmsxnktgzffqgihusjei.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indtc3hua3RnemZmcWdpaHVzamVpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg2ODI3MDksImV4cCI6MjA2NDI1ODcwOX0.nhJ2pzaDr1YqeLSfGL3T1nW_cWduIC8eREqfKM6lXrI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);